import React, { useState, useMemo, useEffect, useRef } from 'react';
import { 
  BookOpen, Compass, Cpu, Heart, User, Lock, Mail, Eye, EyeOff, 
  UserCheck, MessageSquare, Calendar, ChevronRight, Clock, 
  Search, Info, Send, ArrowLeft, ShoppingBag, Award, Trash2, ChefHat
} from 'lucide-react';

const recipeGradients = [
  "from-amber-500 to-rose-500",
  "from-orange-500 to-red-500",
  "from-yellow-500 to-orange-500"
];

const Avatar = ({ name, size = "w-8 h-8", textClass = "text-xs" }) => (
  <div className={`${size} rounded-full bg-rose-500 text-white flex items-center justify-center font-bold ${textClass}`}>
    {name ? name.substring(0, 2).toUpperCase() : "AI"}
  </div>
);

const CoverPlaceholder = ({ gradientClass }) => (
  <div className={`w-full h-full bg-gradient-to-br ${gradientClass || 'from-slate-800 to-slate-900'} flex items-center justify-center`}>
    <ChefHat className="w-12 h-12 text-white/20" />
  </div>
);

// Mock implementation of callGemini or firebase if not imported externally
const callGemini = async (prompt, system) => {
  return JSON.stringify({
    name: "AI Fusion Special",
    cuisine: "Global",
    difficulty: "Easy",
    totalTime: "20 mins",
    description: "Generated by Arbeez Premium AI Kitchen Console.",
    servings: "2 persons",
    ingredients: [{ name: "Main Ingredient", amount: "100", unit: "g" }],
    instructions: [{ step: 1, title: "Prepare", description: "Mix and heat well." }],
    nutrition: { calories: "250", protein: "10g", carbohydrates: "20g", fat: "5g", fiber: "2g" },
    tips: ["Serve hot."]
  });
};

const db = {}, appId = "arbeez-app", auth = { currentUser: null };

export default function App() {
  const [activeTab, setActiveTab] = useState("dashboard");
  const [selectedRecipeDetail, setSelectedRecipeDetail] = useState(null);
  const [recipes, setRecipes] = useState([]);
  const [myCreatedRecipes, setMyCreatedRecipes] = useState([]);
  const [favorites, setFavorites] = useState([]);
  const [shoppingList, setShoppingList] = useState([]);
  const [mealPlan, setMealPlan] = useState({});
  const [profile, setProfile] = useState({ name: "Chef Specialist", username: "chef_special", bio: "Artisan Chef" });
  const [following, setFollowing] = useState([]);
  const [followers, setFollowers] = useState([]);
  const [darkMode, setDarkMode] = useState(false);
  const [user, setUser] = useState({ uid: "guest-uid" });
  const [isAnonymous, setIsAnonymous] = useState(true);
  const [selectedChefUsername, setSelectedChefUsername] = useState("");
  const [followCounts, setFollowCounts] = useState({ followersCount: 0, followingCount: 0 });
  const [totalLikesReceived, setTotalLikesReceived] = useState(0);

  const addToast = (msg, type) => console.log(`[Toast - ${type}]: ${msg}`);
  const handleLikeRecipe = (id) => {};
  const handleToggleFavorite = (rec) => {};
  const handleFollowChef = (uid, uname) => {};

  return (
    <div className={darkMode ? "dark" : ""}>
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 pb-20 md:pb-0">
        <main className="max-w-7xl mx-auto p-4 md:p-8">
          <section className="mb-12">
            {!selectedRecipeDetail && (
              <>
                {activeTab === "dashboard" && (
                  <DashboardView
                    recipes={recipes}
                    myRecipes={myCreatedRecipes}
                    totalLikes={totalLikesReceived}
                    followCounts={followCounts}
                    favorites={favorites}
                    onNavigate={(tab) => {
                      const requiresAuth = ["generate", "upload", "favorites", "meal-planner", "shopping-list"].includes(tab);
                      if (requiresAuth && isAnonymous) {
                        addToast("Please sign in or register to use that feature!", "info");
                        setActiveTab("profile");
                        return;
                      }
                      setActiveTab(tab);
                    }}
                    onSelectRecipe={(rec) => setSelectedRecipeDetail(rec)}
                    onLikeRecipe={(id) => handleLikeRecipe(id)}
                    user={user}
                    isAnonymous={isAnonymous}
                  />
                )}
                
                {activeTab === "discover" && (
                  <DiscoverView
                    recipes={recipes}
                    onSelectRecipe={(rec) => setSelectedRecipeDetail(rec)}
                    onLikeRecipe={(id) => handleLikeRecipe(id)}
                    favorites={favorites}
                    onFavorite={(rec) => handleToggleFavorite(rec)}
                    onChefSelect={(username) => {
                      setSelectedChefUsername(username);
                      setActiveTab("chef-profile");
                    }}
                    user={user}
                    isAnonymous={isAnonymous}
                  />
                )}

                {activeTab === "generate" && !isAnonymous && (
                  <AiRecipeGeneratorView
                    addToast={addToast}
                    user={user}
                    onRecipeCreated={(newRec) => {
                      setRecipes(prev => [newRec, ...prev]);
                      setSelectedRecipeDetail(newRec);
                    }}
                  />
                )}

                {activeTab === "chef-ai" && <AiChefChatView />}

                {activeTab === "upload" && !isAnonymous && (
                  <UploadRecipeView
                    user={user}
                    profile={profile}
                    addToast={addToast}
                    onSuccess={(newRec) => {
                      setSelectedRecipeDetail(newRec);
                    }}
                  />
                )}

                {activeTab === "favorites" && !isAnonymous && (
                  <FavoritesView
                    favorites={favorites}
                    recipes={recipes}
                    onSelectRecipe={(rec) => setSelectedRecipeDetail(rec)}
                    onRemoveFavorite={(rec) => handleToggleFavorite(rec)}
                  />
                )}

                {activeTab === "meal-planner" && !isAnonymous && (
                  <MealPlannerView
                    recipes={recipes}
                    mealPlan={mealPlan}
                    user={user}
                    addToast={addToast}
                  />
                )}

                {activeTab === "shopping-list" && !isAnonymous && (
                  <ShoppingListView
                    shoppingList={shoppingList}
                    user={user}
                    addToast={addToast}
                  />
                )}

                {activeTab === "profile" && (
                  <ChefProfileView
                    profile={profile}
                    myRecipes={myCreatedRecipes}
                    followersCount={followCounts.followersCount}
                    followingCount={followCounts.followingCount}
                    totalLikes={totalLikesReceived}
                    onSelectRecipe={(rec) => setSelectedRecipeDetail(rec)}
                    isAnonymous={isAnonymous}
                    onLoginClick={() => setIsAnonymous(false)}
                  />
                )}

                {activeTab === "chef-profile" && (
                  <PublicChefProfileView
                    selectedUsername={selectedChefUsername}
                    recipes={recipes}
                    user={user}
                    following={following}
                    followers={followers}
                    onFollowChef={(uid, uname) => handleFollowChef(uid, uname)}
                    onBack={() => setActiveTab("discover")}
                    onSelectRecipe={(rec) => setSelectedRecipeDetail(rec)}
                    isAnonymous={isAnonymous}
                  />
                )}

                {activeTab === "settings" && !isAnonymous && (
                  <SettingsView
                    profile={profile}
                    setProfile={setProfile}
                    darkMode={darkMode}
                    setDarkMode={setDarkMode}
                    addToast={addToast}
                    user={user}
                  />
                )}
              </>
            )}
          </section>

          <nav className="md:hidden bg-white dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 fixed bottom-0 left-0 right-0 py-3 px-6 flex justify-between items-center z-40 shadow-xl">
            {[
              { id: "dashboard", label: "Home", icon: BookOpen },
              { id: "discover", label: "Discover", icon: Compass },
              { id: "profile", label: "Profile", icon: User }
            ].map(item => {
              const IconComp = item.icon;
              const isActive = activeTab === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => {
                    setActiveTab(item.id);
                    setSelectedRecipeDetail(null);
                  }}
                  className={`flex flex-col items-center space-y-1 ${isActive ? 'text-rose-500' : 'text-slate-400'}`}
                >
                  <IconComp className="w-5 h-5" />
                  <span className="text-[10px] font-semibold">{item.label}</span>
                </button>
              );
            })}
          </nav>
        </main>
      </div>
    </div>
  );
}

function DashboardView({ recipes, myRecipes, totalLikes, followCounts, favorites, onNavigate, onSelectRecipe, onLikeRecipe, user, isAnonymous }) {
  const trendingRecipes = useMemo(() => {
    return [...recipes].sort((a, b) => (b.likes?.length || 0) - (a.likes?.length || 0)).slice(0, 3);
  }, [recipes]);

  return (
    <div className="space-y-8 animate-fadeIn">
      <div className="relative rounded-3xl overflow-hidden bg-gradient-to-r from-slate-900 to-amber-950 text-white p-8 md:p-12 shadow-2xl">
        <div className="relative z-10 max-w-xl space-y-4">
          <span className="bg-amber-500/20 text-amber-300 font-extrabold text-xs tracking-wider px-3 py-1 rounded-full border border-amber-500/20">PREMIUM AI EXPERTISE</span>
          <h2 className="text-3xl md:text-5xl font-black leading-tight tracking-tight">Create Extraordinary Culinary Masterpieces.</h2>
          <p className="text-slate-300 text-sm md:text-base">Harness the power of Arbeez Chef AI to draft customized recipes, extract grocery indexes, track instant nutrients, and share gourmet craft with friends.</p>
          <div className="pt-2 flex flex-wrap gap-3">
            <button onClick={() => onNavigate("chef-ai")} className="bg-gradient-to-r from-amber-500 to-rose-500 hover:from-amber-600 hover:to-rose-600 text-white font-bold text-sm px-6 py-3 rounded-xl shadow-lg shadow-rose-500/20 transition-transform active:scale-95 flex items-center space-x-2">
              <Cpu className="w-4 h-4" /><span>Launch AI Kitchen</span>
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: "Followers", value: isAnonymous ? 0 : followCounts.followersCount, color: "from-purple-500 to-indigo-500" },
          { label: "Following", value: isAnonymous ? 0 : followCounts.followingCount, color: "from-blue-500 to-teal-500" },
          { label: "Recipes Published", value: isAnonymous ? 0 : myRecipes.length, color: "from-amber-500 to-orange-500" },
          { label: "Hearts Received", value: isAnonymous ? 0 : totalLikes, color: "from-rose-500 to-pink-500" }
        ].map((stat, i) => (
          <div key={i} className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-200 dark:border-slate-800 shadow-sm hover:shadow-md transition-shadow">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">{stat.label}</span>
            <div className="flex items-baseline space-x-2 mt-1">
              <span className={`text-3xl font-extrabold bg-gradient-to-r ${stat.color} bg-clip-text text-transparent`}>{stat.value}</span>
            </div>
          </div>
        ))}
      </div>

      <div>
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-xl font-bold tracking-tight">Trending Community Masterpieces</h3>
          <button onClick={() => onNavigate("discover")} className="text-xs text-rose-500 font-semibold hover:underline">View All Discoveries</button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {trendingRecipes.length === 0 ? (
            <div className="col-span-3 text-center py-12 bg-slate-50 dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800">
              <p className="text-sm text-slate-400 font-medium">No recipes currently uploaded in the public pool. Spark the discovery by generating one!</p>
            </div>
          ) : (
            trendingRecipes.map(recipe => (
              <RecipeCard key={recipe.id} recipe={recipe} onSelect={onSelectRecipe} liked={recipe.likes?.includes(user?.uid)} isAnonymous={isAnonymous} onLikeDirect={onLikeRecipe} />
            ))
          )}
        </div>
      </div>
    </div>
  );
}

function RecipeCard({ recipe, onSelect, liked, isAnonymous, onLikeDirect }) {
  const renderCover = () => {
    const isUrl = recipe.cover?.startsWith('http');
    if (isUrl) return <img src={recipe.cover} alt={recipe.name} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" />;
    return <div className="w-full h-full transition-transform duration-500 group-hover:scale-105"><CoverPlaceholder gradientClass={recipe.cover} /></div>;
  };

  return (
    <div className="bg-white dark:bg-slate-900 rounded-2xl overflow-hidden border border-slate-200 dark:border-slate-800 shadow-sm hover:shadow-xl transition-all group flex flex-col justify-between">
      <div>
        <div className="relative h-48 overflow-hidden bg-slate-100 dark:bg-slate-800">
          {renderCover()}
          <span className="absolute top-3 left-3 bg-white/90 dark:bg-slate-950/95 backdrop-blur-md text-xs font-bold px-3 py-1 rounded-full shadow text-amber-500 dark:text-amber-400">
            {recipe.cuisine || "Global"}
          </span>
          <button
            onClick={(e) => {
              e.stopPropagation();
              if (!isAnonymous) onLikeDirect(recipe.id);
            }}
            className={`absolute top-3 right-3 p-2 rounded-full backdrop-blur-md border shadow transition-colors ${
              liked ? 'bg-rose-500 border-rose-500 text-white' : 'bg-white/95 text-slate-600 hover:text-rose-500 border-slate-200 dark:bg-slate-950/95 dark:border-slate-800'
            }`}
          >
            <Heart className="w-4 h-4" fill={liked ? "currentColor" : "none"} />
          </button>
        </div>
        <div className="p-5 space-y-3">
          <div className="flex items-center space-x-2">
            <span className="bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-300 text-[10px] font-extrabold px-2 py-0.5 rounded tracking-wide uppercase">{recipe.difficulty || "Easy"}</span>
            <span className="text-xs text-slate-400 flex items-center"><Clock className="w-3.5 h-3.5 mr-1 text-slate-400" />{recipe.cookTime || recipe.totalTime || "25 mins"}</span>
          </div>
          <h4 className="font-extrabold text-lg text-slate-950 dark:text-white line-clamp-1 leading-snug">{recipe.name}</h4>
          <p className="text-xs text-slate-400 line-clamp-2">{recipe.description || "Indulge in this gourmet experience prepared to perfection."}</p>
        </div>
      </div>
      <div className="px-5 pb-5 pt-3 border-t border-slate-100 dark:border-slate-800/80 flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <Avatar name={recipe.createdByChef || "AI"} size="w-6 h-6" textClass="text-[8px]" />
          <span className="text-[11px] font-semibold text-slate-500 truncate max-w-[120px]">{recipe.createdByChef || "Arbeez AI Chef"}</span>
        </div>
        <button onClick={() => onSelect(recipe)} className="text-xs font-bold text-rose-500 hover:text-rose-600 transition-colors flex items-center space-x-1">
          <span>View Details</span><ChevronRight className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
}

function DiscoverView({ recipes, onSelectRecipe, onLikeRecipe, favorites, onFavorite, onChefSelect, user, isAnonymous }) {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCuisine, setSelectedCuisine] = useState("All");
  const cuisines = ["All", "Indian", "Italian", "Chinese", "Mexican", "Arabic"];

  const filteredRecipes = useMemo(() => {
    return recipes.filter(rec => {
      const matchesSearch = rec.name?.toLowerCase().includes(searchTerm.toLowerCase()) || rec.description?.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCuisine = selectedCuisine === "All" || rec.cuisine === selectedCuisine;
      return matchesSearch && matchesCuisine;
    });
  }, [recipes, searchTerm, selectedCuisine]);

  return (
    <div className="space-y-6 animate-fadeIn">
      <div className="flex flex-col md:flex-row gap-4 items-center justify-between">
        <div className="relative w-full md:max-w-md">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 w-5 h-5" />
          <input type="text" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} placeholder="Search recipes..." className="w-full pl-11 pr-4 py-3 text-sm bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl focus:outline-none" />
        </div>
        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
          {cuisines.map(c => <button key={c} onClick={() => setSelectedCuisine(c)} className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition-all ${selectedCuisine === c ? 'bg-rose-500 border-rose-500 text-white' : 'bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-300'}`}>{c}</button>)}
        </div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredRecipes.map(recipe => (
          <RecipeCard key={recipe.id} recipe={recipe} onSelect={onSelectRecipe} liked={recipe.likes?.includes(user?.uid)} isAnonymous={isAnonymous} onLikeDirect={onLikeRecipe} />
        ))}
      </div>
    </div>
  );
}

function AiChefChatView() {
  const [messages, setMessages] = useState([{ id: 1, sender: "assistant", text: "Hello! I am your AI Chef Assistant. Let's discuss culinary arts." }]);
  const [inputMessage, setInputMessage] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const handleSendMessage = async (e) => {
    e.preventDefault();
    if (!inputMessage.trim()) return;
    setMessages(prev => [...prev, { id: Date.now(), sender: "user", text: inputMessage }]);
    setInputMessage("");
  };

  return (
    <div className="max-w-4xl mx-auto h-[500px] bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl flex flex-col justify-between overflow-hidden shadow-xl animate-fadeIn">
      <div className="flex-1 overflow-y-auto p-6 space-y-4">
        {messages.map(msg => (
          <div key={msg.id} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`p-4 rounded-2xl max-w-md text-sm ${msg.sender === 'user' ? 'bg-rose-500 text-white' : 'bg-slate-100 dark:bg-slate-800'}`}>
              <div className="text-xs font-medium">{msg.text}</div>
            </div>
          </div>
        ))}
      </div>
      <form onSubmit={handleSendMessage} className="p-4 bg-slate-50 dark:bg-slate-950/40 border-t flex items-center space-x-3">
        <input type="text" value={inputMessage} onChange={(e) => setInputMessage(e.target.value)} placeholder="Ask anything..." className="flex-1 py-3 px-4 text-xs bg-white dark:bg-slate-900 border rounded-xl focus:outline-none" />
        <button type="submit" className="bg-rose-500 text-white p-3 rounded-xl"><Send className="w-4 h-4" /></button>
      </form>
    </div>
  );
}

function AiRecipeGeneratorView() { return <div>AI Generator View Placeholder</div>; }
function FavoritesView() { return <div>Favorites Cookbook View</div>; }
function MealPlannerView() { return <div>Meal Planner View</div>; }
function ShoppingListView() { return <div>Shopping List View</div>; }
function PublicChefProfileView() { return <div>Public Chef Profile View</div>; }
function SettingsView() { return <div>Settings View</div>; }

function ChefProfileView({ profile, myRecipes, followersCount, followingCount, totalLikes, onSelectRecipe, isAnonymous, onLoginClick }) {
  return (
    <div className="space-y-8 animate-fadeIn max-w-5xl mx-auto">
      <div className="relative rounded-3xl overflow-hidden bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-md p-6">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div className="flex items-end space-x-4">
            <Avatar name={profile.name} size="w-24 h-24" textClass="text-3xl" />
            <div>
              <h3 className="text-xl font-bold text-slate-950 dark:text-white leading-tight">{profile.name}</h3>
              <p className="text-xs text-slate-400">@{profile.username}</p>
            </div>
          </div>
        </div>
        {isAnonymous && (
          <div className="pt-4">
            <button onClick={onLoginClick} className="bg-gradient-to-r from-amber-500 to-rose-500 text-white font-bold text-xs px-5 py-2.5 rounded-xl shadow-lg">
              Explore Premium Chef Features
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
function UploadRecipeView() { return <div>Upload Recipe View</div>; }
